"""Initial migration

Revision ID: de3f60427284
Revises: 
Create Date: 2025-09-15 19:46:22.736029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de3f60427284'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('global_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('message_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('has_embeds', sa.Boolean(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_activity_channel_id'), 'message_activity', ['channel_id'], unique=False)
    op.create_index(op.f('ix_message_activity_guild_id'), 'message_activity', ['guild_id'], unique=False)
    op.create_index(op.f('ix_message_activity_message_id'), 'message_activity', ['message_id'], unique=True)
    op.create_index(op.f('ix_message_activity_sent_at'), 'message_activity', ['sent_at'], unique=False)
    op.create_index(op.f('ix_message_activity_user_id'), 'message_activity', ['user_id'], unique=False)
    op.create_table('presence_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('previous_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('activity_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presence_activity_changed_at'), 'presence_activity', ['changed_at'], unique=False)
    op.create_index(op.f('ix_presence_activity_guild_id'), 'presence_activity', ['guild_id'], unique=False)
    op.create_index(op.f('ix_presence_activity_user_id'), 'presence_activity', ['user_id'], unique=False)
    op.create_table('user_name_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('old_username', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('new_username', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('old_display_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('new_display_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('old_global_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('new_global_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('change_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name_history_changed_at'), 'user_name_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_user_name_history_user_id'), 'user_name_history', ['user_id'], unique=False)
    op.create_table('voice_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('was_muted', sa.Boolean(), nullable=False),
    sa.Column('was_deafened', sa.Boolean(), nullable=False),
    sa.Column('was_streaming', sa.Boolean(), nullable=False),
    sa.Column('was_video', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_activity_channel_id'), 'voice_activity', ['channel_id'], unique=False)
    op.create_index(op.f('ix_voice_activity_guild_id'), 'voice_activity', ['guild_id'], unique=False)
    op.create_index(op.f('ix_voice_activity_joined_at'), 'voice_activity', ['joined_at'], unique=False)
    op.create_index(op.f('ix_voice_activity_user_id'), 'voice_activity', ['user_id'], unique=False)
    # ### end Alembic commands ###
    
    # Insert test data
    from datetime import datetime, timezone
    
    # Test users
    op.bulk_insert(
        sa.table('users',
            sa.column('user_id', sa.BigInteger),
            sa.column('username', sa.String),
            sa.column('display_name', sa.String),
            sa.column('global_name', sa.String),
            sa.column('first_seen', sa.DateTime),
            sa.column('last_updated', sa.DateTime)
        ),
        [
            {
                'user_id': 123456789012345678,
                'username': 'john_doe',
                'display_name': 'John',
                'global_name': 'JohnDoe2024',
                'first_seen': datetime(2024, 1, 15, 10, 30, 0, tzinfo=timezone.utc),
                'last_updated': datetime(2024, 1, 15, 10, 30, 0, tzinfo=timezone.utc)
            },
            {
                'user_id': 987654321098765432,
                'username': 'jane_smith',
                'display_name': 'Jane',
                'global_name': 'JaneSmith',
                'first_seen': datetime(2024, 1, 16, 14, 20, 0, tzinfo=timezone.utc),
                'last_updated': datetime(2024, 1, 16, 14, 20, 0, tzinfo=timezone.utc)
            }
        ]
    )
    
    # Test message activity
    op.bulk_insert(
        sa.table('message_activity',
            sa.column('user_id', sa.BigInteger),
            sa.column('guild_id', sa.BigInteger),
            sa.column('channel_id', sa.BigInteger),
            sa.column('message_id', sa.BigInteger),
            sa.column('message_type', sa.String),
            sa.column('has_attachments', sa.Boolean),
            sa.column('has_embeds', sa.Boolean),
            sa.column('character_count', sa.Integer),
            sa.column('sent_at', sa.DateTime)
        ),
        [
            {
                'user_id': 123456789012345678,
                'guild_id': 555666777888999000,
                'channel_id': 111222333444555666,
                'message_id': 777888999000111222,
                'message_type': 'default',
                'has_attachments': False,
                'has_embeds': False,
                'character_count': 23,
                'sent_at': datetime(2024, 1, 15, 15, 45, 0, tzinfo=timezone.utc)
            },
            {
                'user_id': 987654321098765432,
                'guild_id': 555666777888999000,
                'channel_id': 111222333444555666,
                'message_id': 333444555666777888,
                'message_type': 'reply',
                'has_attachments': True,
                'has_embeds': False,
                'character_count': 156,
                'sent_at': datetime(2024, 1, 16, 16, 30, 0, tzinfo=timezone.utc)
            }
        ]
    )
    
    # Test voice activity
    op.bulk_insert(
        sa.table('voice_activity',
            sa.column('user_id', sa.BigInteger),
            sa.column('guild_id', sa.BigInteger),
            sa.column('channel_id', sa.BigInteger),
            sa.column('joined_at', sa.DateTime),
            sa.column('left_at', sa.DateTime),
            sa.column('duration_seconds', sa.Integer),
            sa.column('was_muted', sa.Boolean),
            sa.column('was_deafened', sa.Boolean),
            sa.column('was_streaming', sa.Boolean),
            sa.column('was_video', sa.Boolean)
        ),
        [
            {
                'user_id': 123456789012345678,
                'guild_id': 555666777888999000,
                'channel_id': 999888777666555444,
                'joined_at': datetime(2024, 1, 15, 20, 0, 0, tzinfo=timezone.utc),
                'left_at': datetime(2024, 1, 15, 22, 30, 0, tzinfo=timezone.utc),
                'duration_seconds': 9000,  # 2.5 hours
                'was_muted': False,
                'was_deafened': False,
                'was_streaming': True,
                'was_video': False
            },
            {
                'user_id': 987654321098765432,
                'guild_id': 555666777888999000,
                'channel_id': 999888777666555444,
                'joined_at': datetime(2024, 1, 16, 19, 15, 0, tzinfo=timezone.utc),
                'left_at': None,  # Still in channel
                'duration_seconds': None,
                'was_muted': True,
                'was_deafened': False,
                'was_streaming': False,
                'was_video': True
            }
        ]
    )
    
    # Test presence activity
    op.bulk_insert(
        sa.table('presence_activity',
            sa.column('user_id', sa.BigInteger),
            sa.column('guild_id', sa.BigInteger),
            sa.column('status', sa.String),
            sa.column('previous_status', sa.String),
            sa.column('activity_type', sa.String),
            sa.column('activity_name', sa.String),
            sa.column('changed_at', sa.DateTime),
            sa.column('duration_seconds', sa.Integer)
        ),
        [
            {
                'user_id': 123456789012345678,
                'guild_id': 555666777888999000,
                'status': 'online',
                'previous_status': 'offline',
                'activity_type': 'playing',
                'activity_name': 'Minecraft',
                'changed_at': datetime(2024, 1, 15, 14, 0, 0, tzinfo=timezone.utc),
                'duration_seconds': 3600
            },
            {
                'user_id': 987654321098765432,
                'guild_id': 555666777888999000,
                'status': 'dnd',
                'previous_status': 'online',
                'activity_type': 'listening',
                'activity_name': 'Spotify',
                'changed_at': datetime(2024, 1, 16, 18, 0, 0, tzinfo=timezone.utc),
                'duration_seconds': 7200
            }
        ]
    )
    
    # Test username history
    op.bulk_insert(
        sa.table('user_name_history',
            sa.column('user_id', sa.BigInteger),
            sa.column('old_username', sa.String),
            sa.column('new_username', sa.String),
            sa.column('old_display_name', sa.String),
            sa.column('new_display_name', sa.String),
            sa.column('change_type', sa.String),
            sa.column('changed_at', sa.DateTime),
            sa.column('guild_id', sa.BigInteger)
        ),
        [
            {
                'user_id': 123456789012345678,
                'old_username': 'john_d',
                'new_username': 'john_doe',
                'old_display_name': None,
                'new_display_name': None,
                'change_type': 'username',
                'changed_at': datetime(2024, 1, 10, 12, 0, 0, tzinfo=timezone.utc),
                'guild_id': None
            }
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_activity_user_id'), table_name='voice_activity')
    op.drop_index(op.f('ix_voice_activity_joined_at'), table_name='voice_activity')
    op.drop_index(op.f('ix_voice_activity_guild_id'), table_name='voice_activity')
    op.drop_index(op.f('ix_voice_activity_channel_id'), table_name='voice_activity')
    op.drop_table('voice_activity')
    op.drop_index(op.f('ix_user_name_history_user_id'), table_name='user_name_history')
    op.drop_index(op.f('ix_user_name_history_changed_at'), table_name='user_name_history')
    op.drop_table('user_name_history')
    op.drop_index(op.f('ix_presence_activity_user_id'), table_name='presence_activity')
    op.drop_index(op.f('ix_presence_activity_guild_id'), table_name='presence_activity')
    op.drop_index(op.f('ix_presence_activity_changed_at'), table_name='presence_activity')
    op.drop_table('presence_activity')
    op.drop_index(op.f('ix_message_activity_user_id'), table_name='message_activity')
    op.drop_index(op.f('ix_message_activity_sent_at'), table_name='message_activity')
    op.drop_index(op.f('ix_message_activity_message_id'), table_name='message_activity')
    op.drop_index(op.f('ix_message_activity_guild_id'), table_name='message_activity')
    op.drop_index(op.f('ix_message_activity_channel_id'), table_name='message_activity')
    op.drop_table('message_activity')
    op.drop_table('users')
    # ### end Alembic commands ###
